language: python
python:
  - 2.7

branches:
  only:
    - master
    - /^build-master-jewel-*/

services:
  - docker


before_install:
  - docker --version
  - sudo apt-get install -y --force-yes xfsprogs
  - sudo ./travis-builds/purge_cluster.sh
  - sudo ./travis-builds/build_imgs.sh

# NOTE(leseb): somehow putting everything in a 'script' task does not work
# so we have to split it up that way.
# It seems that we have an issue when not running 'docker run' from an install step
install:
  - sudo ./travis-builds/prepare_osd_fs.sh
  - docker run -d --name ceph-mon --net=host -v /etc/ceph:/etc/ceph -v /var/lib/ceph:/var/lib/ceph -e MON_IP=$(ip -4 -o a | awk '/eth|ens|eno|enp/ { sub ("/..", "", $4); print $4 }') -e CEPH_PUBLIC_NETWORK=$(grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/[0-9]\{1,2\}' /proc/net/fib_trie | grep -vE "^127|0$" | head -1) daemon mon
  - sudo ./travis-builds/bootstrap_osd.sh
  - docker run -d --name ceph-osd --net=host -v /etc/ceph:/etc/ceph -v /var/lib/ceph:/var/lib/ceph daemon osd_directory_single
  - docker run -d --name ceph-mds --net=host -v /etc/ceph:/etc/ceph -v /var/lib/ceph:/var/lib/ceph -e CEPHFS_CREATE=1 daemon mds
  - docker run -d --name ceph-rgw --net=host -v /etc/ceph:/etc/ceph -v /var/lib/ceph:/var/lib/ceph daemon rgw

script:
  - sudo ./travis-builds/validate_cluster.sh
  - sudo ./travis-builds/purge_cluster.sh
  - sudo ./travis-builds/prepare_osd_fs.sh
  - docker run -d --name ceph-demo --net=host -v /etc/ceph:/etc/ceph -v /var/lib/ceph:/var/lib/ceph -e MON_IP=$(ip -4 -o a | awk '/eth|ens|eno|enp/ { sub ("/..", "", $4); print $4 }') -e CEPH_PUBLIC_NETWORK=$(grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/[0-9]\{1,2\}' /proc/net/fib_trie | grep -vE "^127|0$" | head -1) demo
  - sudo ./travis-builds/validate_demo_cluster.sh

after_failure:
  - docker images
  - docker ps
  - docker ps -a
  - docker logs ceph-mon
  - docker logs ceph-osd
  - docker logs ceph-mds
  - docker logs ceph-rgw
  - docker logs ceph-demo
  - docker exec ceph-mon ceph -s
  - docker exec ceph-demo ceph -s

after_success:
  - docker exec ceph-mon ceph -s
  - docker exec ceph-demo ceph -s
